# Generated by Django 3.2.14 on 2023-02-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chair_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patients_Name', models.CharField(max_length=255)),
                ('Patients_Age', models.CharField(max_length=11, null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False)),
                ('Chair_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.chairnumber')),
                ('Treatment_Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.treatmentcategory')),
            ],
        ),
    ]
