# Generated by Django 3.2.14 on 2023-02-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=11)),
                ('status', models.BooleanField(default=False)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.patientlist')),
            ],
        ),
    ]
