# Generated by Django 3.2.14 on 2023-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_tokengenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokengenerator',
            name='call_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
